# MinecraftAgent設定ファイル

# データベース設定
database:
  type: sqlite # sqlite, mysql
  sqlite:
    file: "plugins/MinecraftAgent/data.db"
  mysql:
    host: "localhost"
    port: 3306
    database: "minecraft_agent"
    username: "root"
    password: ""

# エージェント設定
agent:
  # 最大同時稼働エージェント数
  max_agents: 10
  
  # デフォルト行動設定
  default_behavior:
    # 生存行動
    survival:
      enabled: true
      priority: 100
      health_threshold: 10
      food_threshold: 10
    
    # 資源収集行動
    resource_gathering:
      enabled: true
      priority: 80
      items:
        - "minecraft:oak_log"
        - "minecraft:stone"
        - "minecraft:coal_ore"
        - "minecraft:iron_ore"
        - "minecraft:diamond_ore"
    
    # 探索行動
    exploration:
      enabled: true
      priority: 60
      radius: 100
      interval_seconds: 30
    
    # 建築行動
    building:
      enabled: false
      priority: 40
  
  # 移動設定
  movement:
    speed: 1.0
    jump_height: 1.25
    step_height: 0.6
  
  # 戦闘設定
  combat:
    enabled: true
    auto_defend: true
    flee_health: 5
    attack_mobs: true
    attack_players: false

# ログ設定
logging:
  level: INFO # DEBUG, INFO, WARN, ERROR
  file: true
  console: true

# パフォーマンス設定
performance:
  # タスク実行間隔（ティック）
  task_interval: 20
  # チャンク読み込み範囲
  chunk_radius: 3
  # エンティティ検索範囲
  entity_search_radius: 16